// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfectCareer.Web.Data;

#nullable disable

namespace PerfectCareer.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920091347_AddPositions")]
    partial class AddPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Attributes.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AttributeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 3,
                            DataType = 1,
                            Description = "Candidate's first name.",
                            IsBuiltIn = true,
                            Name = "First Name"
                        },
                        new
                        {
                            Id = 2,
                            Category = 3,
                            DataType = 1,
                            Description = "Candidate's last name.",
                            IsBuiltIn = true,
                            Name = "Last Name"
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            DataType = 1,
                            Description = "Candidate's current location.",
                            IsBuiltIn = true,
                            Name = "Location"
                        },
                        new
                        {
                            Id = 4,
                            Category = 3,
                            DataType = 3,
                            Description = "Candidate's personal photo.",
                            IsBuiltIn = true,
                            Name = "Personal Photo"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            DataType = 4,
                            Description = "Candidate's IELTS score.",
                            IsBuiltIn = false,
                            Name = "IELTS Score"
                        },
                        new
                        {
                            Id = 6,
                            Category = 4,
                            DataType = 8,
                            Description = "Candidate's presentation skill level.",
                            IsBuiltIn = false,
                            Name = "Presentation Skills"
                        },
                        new
                        {
                            Id = 7,
                            Category = 3,
                            DataType = 7,
                            Description = "Whether the candidate is available for remote work.",
                            IsBuiltIn = false,
                            Name = "Remote Work Availability"
                        },
                        new
                        {
                            Id = 8,
                            Category = 3,
                            DataType = 2,
                            Description = "A concise overview of the candidate's professional background and career goals.",
                            IsBuiltIn = false,
                            Name = "Professional Summary"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            DataType = 1,
                            Description = "The candidate's GitHub profile URL or username.",
                            IsBuiltIn = false,
                            Name = "GitHub Profile"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            DataType = 4,
                            Description = "The candidate's total years of professional experience.",
                            IsBuiltIn = false,
                            Name = "Years of Experience"
                        },
                        new
                        {
                            Id = 11,
                            Category = 3,
                            DataType = 5,
                            Description = "The date when the candidate is available to start a new position.",
                            IsBuiltIn = false,
                            Name = "Available Start Date"
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            DataType = 6,
                            Description = "The start and end dates of the candidate's most relevant experience.",
                            IsBuiltIn = false,
                            Name = "Relevant Experience Period"
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            DataType = 7,
                            Description = "Whether the candidate is willing to relocate for a position.",
                            IsBuiltIn = false,
                            Name = "Open to Relocation"
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            DataType = 8,
                            Description = "The candidate's overall English proficiency level.",
                            IsBuiltIn = false,
                            Name = "English Level"
                        });
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Attributes.AttributeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId", "Label")
                        .IsUnique();

                    b.ToTable("AttributeOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttributeDefinitionId = 6,
                            Label = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            AttributeDefinitionId = 6,
                            Label = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            AttributeDefinitionId = 6,
                            Label = "Advanced"
                        },
                        new
                        {
                            Id = 4,
                            AttributeDefinitionId = 14,
                            Label = "Beginner"
                        },
                        new
                        {
                            Id = 5,
                            AttributeDefinitionId = 14,
                            Label = "Intermediate"
                        },
                        new
                        {
                            Id = 6,
                            AttributeDefinitionId = 14,
                            Label = "Upper-Intermediate"
                        },
                        new
                        {
                            Id = 7,
                            AttributeDefinitionId = 14,
                            Label = "Advanced"
                        },
                        new
                        {
                            Id = 8,
                            AttributeDefinitionId = 14,
                            Label = "Fluent"
                        });
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Positions.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "UpdatedAtUtc");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 20, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Build and maintain modern web applications using ASP.NET Core and Entity Framework Core.",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Location = "Riyadh, Saudi Arabia",
                            Title = "Junior ASP.NET Core Developer",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 20, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create responsive, accessible user interfaces for the Perfect Career platform.",
                            EmploymentType = "Full-time",
                            IsActive = true,
                            Location = "Remote",
                            Title = "Frontend Developer",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 20, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Positions.PositionTechnologyTag", b =>
                {
                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyTagId")
                        .HasColumnType("int");

                    b.HasKey("PositionId", "TechnologyTagId");

                    b.HasIndex("TechnologyTagId");

                    b.ToTable("PositionTechnologyTags");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Positions.PositionTemplateAttribute", b =>
                {
                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("PositionId", "AttributeDefinitionId");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("PositionId", "DisplayOrder")
                        .IsUnique();

                    b.ToTable("PositionTemplateAttributes");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            AttributeDefinitionId = 8,
                            DisplayOrder = 1
                        },
                        new
                        {
                            PositionId = 1,
                            AttributeDefinitionId = 9,
                            DisplayOrder = 2
                        },
                        new
                        {
                            PositionId = 1,
                            AttributeDefinitionId = 10,
                            DisplayOrder = 3
                        },
                        new
                        {
                            PositionId = 1,
                            AttributeDefinitionId = 14,
                            DisplayOrder = 4
                        },
                        new
                        {
                            PositionId = 2,
                            AttributeDefinitionId = 8,
                            DisplayOrder = 1
                        },
                        new
                        {
                            PositionId = 2,
                            AttributeDefinitionId = 9,
                            DisplayOrder = 2
                        },
                        new
                        {
                            PositionId = 2,
                            AttributeDefinitionId = 14,
                            DisplayOrder = 3
                        });
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateAttributeUsage", b =>
                {
                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastUsedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CandidateProfileId", "AttributeDefinitionId");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("CandidateProfileId", "LastUsedAtUtc");

                    b.ToTable("CandidateAttributeUsages");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<decimal?>("NumberValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<string>("TextValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId", "SelectedOptionId");

                    b.HasIndex("CandidateProfileId", "AttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("CandidateAttributeValues");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PersonalPhotoPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersonalPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.CandidateProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("CandidateProjects", t =>
                        {
                            t.HasCheckConstraint("CK_CandidateProjects_Period", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.CandidateProjectTechnologyTag", b =>
                {
                    b.Property<int>("CandidateProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyTagId")
                        .HasColumnType("int");

                    b.HasKey("CandidateProjectId", "TechnologyTagId");

                    b.HasIndex("TechnologyTagId");

                    b.ToTable("CandidateProjectTechnologyTags");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.TechnologyTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TechnologyTags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Attributes.AttributeOption", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Positions.PositionTechnologyTag", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Positions.Position", "Position")
                        .WithMany("PositionTechnologyTags")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectCareer.Web.Models.Projects.TechnologyTag", "TechnologyTag")
                        .WithMany()
                        .HasForeignKey("TechnologyTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("TechnologyTag");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Positions.PositionTemplateAttribute", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerfectCareer.Web.Models.Positions.Position", "Position")
                        .WithMany("TemplateAttributes")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateAttributeUsage", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectCareer.Web.Models.Profiles.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateAttributeValue", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Attributes.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerfectCareer.Web.Models.Profiles.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectCareer.Web.Models.Attributes.AttributeOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId", "SelectedOptionId")
                        .HasPrincipalKey("AttributeDefinitionId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AttributeDefinition");

                    b.Navigation("CandidateProfile");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("PerfectCareer.Web.Models.Profiles.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.CandidateProject", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Profiles.CandidateProfile", "CandidateProfile")
                        .WithMany("Projects")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.CandidateProjectTechnologyTag", b =>
                {
                    b.HasOne("PerfectCareer.Web.Models.Projects.CandidateProject", "CandidateProject")
                        .WithMany("ProjectTechnologyTags")
                        .HasForeignKey("CandidateProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectCareer.Web.Models.Projects.TechnologyTag", "TechnologyTag")
                        .WithMany("ProjectTechnologyTags")
                        .HasForeignKey("TechnologyTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProject");

                    b.Navigation("TechnologyTag");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Positions.Position", b =>
                {
                    b.Navigation("PositionTechnologyTags");

                    b.Navigation("TemplateAttributes");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Profiles.CandidateProfile", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.CandidateProject", b =>
                {
                    b.Navigation("ProjectTechnologyTags");
                });

            modelBuilder.Entity("PerfectCareer.Web.Models.Projects.TechnologyTag", b =>
                {
                    b.Navigation("ProjectTechnologyTags");
                });
#pragma warning restore 612, 618
        }
    }
}
